# Generated by Django 6.0.7 on 2026-07-27 05:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gallery Category',
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('short_description', models.CharField(blank=True, help_text='Short teaser shown on cards/listing pages.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Full description shown on the service detail page.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('price', models.DecimalField(decimal_places=2, help_text="Starting price in ₹. Use 0 if price is 'On Request'.", max_digits=9)),
                ('price_on_request', models.BooleanField(default=False, help_text="If checked, shows 'On Request' instead of the price.")),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Approx. duration in minutes.')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this service on the home page.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.ImageField(blank=True, help_text='Small square icon representing the category (optional).', null=True, upload_to='categories/icons/')),
                ('description', models.CharField(blank=True, help_text='One-line description shown under the category name.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default="Hunny's Makeover Studio", max_length=150)),
                ('tagline', models.CharField(default='Where Every Look Tells a Story', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_heading', models.CharField(default='Beauty, Tailored to You', max_length=200)),
                ('hero_subheading', models.CharField(default='Bridal & party makeup, hairstyling and skin care in an elegant, private studio setting.', max_length=300)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('about_title', models.CharField(default='The Studio Story', max_length=200)),
                ('about_text', models.TextField(default="Hunny's Makeover Studio was founded on a simple belief: every client deserves to feel like the most beautiful version of themselves. From intimate bridal mornings to glamorous party looks, our artists blend technique with heart to create looks that photograph beautifully and last all day.")),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('years_experience', models.PositiveIntegerField(default=8)),
                ('happy_clients', models.PositiveIntegerField(default=2500)),
                ('services_offered', models.PositiveIntegerField(default=20)),
                ('phone', models.CharField(default='+91 90000 00000', max_length=20)),
                ('whatsapp_number', models.CharField(default='919000000000', help_text='Digits only, with country code, no + or spaces (used in wa.me links).', max_length=20)),
                ('email', models.EmailField(default='hello@hunnysmakeoverstudio.com', max_length=254)),
                ('address', models.CharField(default='123 Rosewood Lane, Vadodara, Gujarat', max_length=255)),
                ('google_maps_embed_url', models.URLField(blank=True, help_text='Paste a Google Maps embed URL.')),
                ('opening_hours', models.CharField(default='Tue - Sun: 10:00 AM - 8:00 PM (Mon Closed)', max_length=255)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('pinterest_url', models.URLField(blank=True)),
                ('footer_note', models.CharField(default='Studio & at-home appointments available.', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(help_text='e.g. Founder & Lead Makeup Artist', max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('instagram_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='studio.gallerycategory')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('location_preference', models.CharField(choices=[('studio', 'At the Studio'), ('home', 'At Home / Venue')], default='studio', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Any special requests from the client.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='studio.service')),
            ],
            options={
                'ordering': ['-preferred_date', '-preferred_time'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='studio.servicecategory'),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=150)),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField()),
                ('is_approved', models.BooleanField(default=False, help_text='Only approved testimonials are shown on the website.')),
                ('is_featured', models.BooleanField(default=False, help_text='Show prominently on the home page.')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='studio.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
